### ISSUE TITLE
Can you add cooldown

### ISSUE THREAD

**Issue by RealMaMo1086** [Mr-Zanzibar/Fake-BTC#2]
It's too quick, can you please add a cooldown? I want to troll my friend but it's way to quick he'll get suspicious.

**Comment by Mr-Zanzibar** [comment]
you can add it yourself

to slow down the whole build process you can open the code
go into string 97 add this
"time.sleep(0.1)"

![Immagine 2023-03-11 222748](https://user-images.githubusercontent.com/104436099/224512304-82e442a6-2ca2-4ef9-99e5-1a5cedd700f0.png)

**Comment by Mr-Zanzibar** [comment]
if you want to make it even slower go from 0.1 to 0.2 etc..

then I also advise you not to put a high number at the " hit at "  because it will be really slower
